// Mocks generated by Mockito 5.4.6 from annotations
// in obo_mne/test/github_stats_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:obo_mne/models/github_profile.dart' as _i2;
import 'package:obo_mne/repositories/github_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGitHubProfile_0 extends _i1.SmartFake implements _i2.GitHubProfile {
  _FakeGitHubProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GitHubRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubRepository extends _i1.Mock implements _i3.GitHubRepository {
  MockGitHubRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GitHubProfile> getGitHubProfile(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubProfile, [username]),
            returnValue: _i4.Future<_i2.GitHubProfile>.value(
              _FakeGitHubProfile_0(
                this,
                Invocation.method(#getGitHubProfile, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.GitHubProfile>);

  @override
  _i4.Future<Map<String, dynamic>> getGitHubStats(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubStats, [username]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getGitHubStatsMock(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getGitHubStatsMock, [username]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
